services:
  showzen-web:
    image: showzen-web:latest
    container_name: showzen-web
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local      
    ports:
      - "4200:80"
    depends_on:
      - showzen-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network  

  showzen-api:
    image: showzen-api:latest
    container_name: showzen-api-container
    build:
      context: ../../
      dockerfile: ShowZen/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44353
      - App__HealthCheckUrl=http://showzen:8080/health-status
      - AuthServer__Authority=http://showzen-api:8080
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__SetSelfAsIssuer=true 
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=ShowZen;Pooling=false;
    ports:
      - "44353:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network  
  
  db-migrator:
    image: showzen-api:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: ShowZen/Dockerfile.local
    environment:
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=ShowZen;Pooling=false;
    command:
      - --migrate-database
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - abp-network
  postgres:
    container_name: postgres-db
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myPassw0rd"
    volumes:
      - postgres_data:/var/opt/postgres
    networks:
      - abp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
    name: showzen_postgres_data
networks:
  abp-network:
    name: showzen-network
    driver: bridge